# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba01f8308acf72da9c3e6541815b9cf7bb8cb628a8ec262ba21733b12f4a0e7d08865a0eaf2fabede2bfc4b30f64038bfc281508738eb360da9c763a1fc9a86c

test:
  secret_key_base: 5be658dd43284ece9bc994e9a0674244eceb0ff8d65312f8c95722da823c52369aca6d455f1203aedf7c9ef77d6d6d6a127c3c4b176a072ba9239c0dfa74ccc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
